language: generic
matrix:
  include:
    - env:
        - BOARD = "arduino:avr:uno"
    - env:
        - BOARD = "Seeeduino:samd:seeed_XIAO_m0"
# default phases
before_install:
  - mkdir -p "$HOME/bin"
  - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR="$HOME/bin" sh
  - export PATH="$PATH:$HOME/bin"
  - arduino-cli core update-index --additional-urls https://downloads.arduino.cc/packages/package_index.json
  - arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/Seeed-Studio/Seeed_Platform/master/package_seeeduino_boards_index.json
  - arduino-cli  core install arduino:avr --additional-urls https://downloads.arduino.cc/packages/package_index.json
  - arduino-cli  core install Seeeduino:samd --additional-urls https://raw.githubusercontent.com/Seeed-Studio/Seeed_Platform/master/package_seeeduino_boards_index.json
  - |
    installLibrary() {
      local -r repositoryFullName="$1"
      local -r repositoryName="${repositoryFullName##*/}"
      # clone repository to the libraries folder of the sketchbook
      git clone https://github.com/${repositoryFullName} "${HOME}/Arduino/libraries/${repositoryName}"
      cd "${HOME}/Arduino/libraries/${repositoryName}"
      cd "${TRAVIS_BUILD_DIR}"
    }
- installLibrary Seeeed-Studio/Seeed_Arduino_atWiFi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch WiFiClientBasic;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch WiFiClient;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch SimpleWiFiServer;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch WiFiAccessPoint;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch WiFiBlueToothSwitch;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch WPS;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch WiFiScan;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch WiFiClientEnterprise;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch WiFiMulti;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch ETH_TLK110;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch WiFiIPv6;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch WiFiClientStaticIP;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch WiFiTelnetToSerial;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch ETH_LAN8720;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch WiFiUDPClient;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch WiFiSmartConfig;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch WiFiClientEvents;
      fi
    - |
      if [ "$BOARD" == "arduino:avr:uno" ]; then
        buildExampleSketch ETH_LAN8720_internal_clock;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch WiFiClientBasic;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch WiFiClient;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch SimpleWiFiServer;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch WiFiAccessPoint;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch WiFiBlueToothSwitch;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch WPS;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch WiFiScan;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch WiFiClientEnterprise;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch WiFiMulti;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch ETH_TLK110;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch WiFiIPv6;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch WiFiClientStaticIP;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch WiFiTelnetToSerial;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch ETH_LAN8720;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch WiFiUDPClient;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch WiFiSmartConfig;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch WiFiClientEvents;
      fi
    - |
      if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
        buildExampleSketch ETH_LAN8720_internal_clock;
      fi
notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always

